[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["multipart"] }
axum-vite = "0.3.4"
chrono = { version = "0.4.45", features = ["now", "serde"] }
dotenvy = "0.15.7"
getifs = "0.6.1"
include_dir = "0.7.4"
reqwest = "0.13.4"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full", "macros"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
sqlx = { version = "0.9.0", features = [
    "runtime-tokio",
    "sqlite",
    "macros",
    "chrono",
] }
serde_json = "1.0.151"
